# Generated by Django 3.0.8 on 2020-10-25 14:57

from django.db import migrations, models
import django.db.models.deletion
from api_questions.constants import Questions


def load_questions(apps, schema_editor):
    question_model = apps.get_model('api_questions', 'Questions')
    i = 0
    for question in Questions.QUESTIONS:
        question_model.objects.create(id=i, content=question.get('content'),\
                                      required=question.get('required'), multiple=question.get('multiple'),\
                                      spec=question.get('spec'))
        i += 1


def load_options(apps, schema_editor):
    question_model = apps.get_model('api_questions', 'Questions')
    option_model = apps.get_model('api_questions', 'Answers')
    i = 0
    for question in Questions.QUESTIONS:
        question1 = question_model.objects.get(pk=i)
        for option in question.get('options'):
            option_model.objects.create(content=option, question=question1)
        i += 1


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('required', models.BooleanField(default=True)),
                ('multiple', models.BooleanField(default=True)),
                ('spec', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='api_questions.Questions')),
            ],
        ),
        migrations.RunPython(load_questions),
        migrations.RunPython(load_options),

    ]
