# Generated by Django 3.0.8 on 2020-11-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_questions', '0002_auto_20201025_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
