# Generated by Django 3.0.8 on 2020-11-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_questions', '0003_auto_20201119_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='train',
            field=models.BooleanField(default=False),
        ),
    ]
