# Generated by Django 3.0.8 on 2020-12-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_questions', '0004_questions_train'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
