# Generated by Django 3.0.8 on 2020-10-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CpuScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cpu_score',
            },
        ),
        migrations.CreateModel(
            name='GpuScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('memory_size', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'gpu_score',
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('rating_average', models.CharField(blank=True, max_length=255, null=True)),
                ('rating_count', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('dimension', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('cpu', models.CharField(blank=True, max_length=255, null=True)),
                ('display', models.CharField(blank=True, max_length=255, null=True)),
                ('screen_size', models.CharField(blank=True, max_length=255, null=True)),
                ('vga', models.CharField(blank=True, max_length=255, null=True)),
                ('disk', models.CharField(blank=True, max_length=255, null=True)),
                ('ram', models.CharField(blank=True, max_length=255, null=True)),
                ('battery', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'laptop',
            },
        ),
    ]
