# Generated by Django 3.0.8 on 2020-10-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopId',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('link', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'laptop_id',
            },
        ),
    ]
