# Generated by Django 3.0.8 on 2020-10-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0002_laptopid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='rating_count',
            new_name='review_count',
        ),
    ]
