# Generated by Django 3.0.8 on 2020-10-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0004_auto_20201022_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='dimension',
            field=models.TextField(blank=True, null=True),
        ),
    ]
