# Generated by Django 3.0.8 on 2020-10-25 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0005_auto_20201023_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpuscore',
            name='memory_size',
        ),
    ]
