# Generated by Django 3.0.8 on 2020-10-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0006_remove_gpuscore_memory_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopBackup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('stock', models.IntegerField(blank=True, default=0, null=True)),
                ('rating_average', models.CharField(blank=True, max_length=255, null=True)),
                ('review_count', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('dimension', models.TextField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('cpu', models.CharField(blank=True, max_length=255, null=True)),
                ('display', models.CharField(blank=True, max_length=255, null=True)),
                ('screen_size', models.CharField(blank=True, max_length=255, null=True)),
                ('vga', models.CharField(blank=True, max_length=255, null=True)),
                ('disk', models.CharField(blank=True, max_length=255, null=True)),
                ('ram', models.CharField(blank=True, max_length=255, null=True)),
                ('battery', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'laptop_backup',
            },
        ),
    ]
