# Generated by Django 3.0.8 on 2020-11-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0007_laptopbackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptopid',
            name='thumbnails',
            field=models.CharField(default='', max_length=255),
        ),
    ]
