# Generated by Django 3.0.8 on 2020-11-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0008_laptopid_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='train',
            field=models.BooleanField(default=False),
        ),
    ]
