# Generated by Django 3.0.8 on 2020-11-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0010_laptop_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='purpose_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
