# Generated by Django 3.0.8 on 2020-12-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0011_laptop_purpose_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptopbackup',
            name='purpose_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laptopbackup',
            name='seller',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laptopbackup',
            name='train',
            field=models.BooleanField(default=False),
        ),
    ]
