# Generated by Django 3.0.8 on 2020-12-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0013_auto_20201206_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopbackup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
