# Generated by Django 3.0.8 on 2020-12-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0014_auto_20201206_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptopid',
            name='product_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='laptopid',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
