# Generated by Django 3.0.8 on 2020-12-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0015_auto_20201206_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='laptop',
            name='thumbnails',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='laptopbackup',
            name='link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='laptopbackup',
            name='thumbnails',
            field=models.CharField(default='', max_length=255),
        ),
    ]
